// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caqudrpcjanvziavudmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhcXVkcnBjamFudnppYXZ1ZG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDI0NzMsImV4cCI6MjA2MTc3ODQ3M30.B9ov_QcnM6NE3ZnoG24oL-_ru8MPcgfLu56zGAaMnBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);